CREATE TABLE ORGANIZATIONS_TYPES (
    TYPE VARCHAR2(30),
    CONSTRAINT ORGANIZATIONS_TYPES_PK PRIMARY KEY (TYPE)
);
CREATE TABLE ORGANIZATIONS (
    ID NUMBER(6,0) NOT NULL,
    TITLE VARCHAR2(50) NOT NULL,
    CONTACT_PERSON_ID NUMBER(6,0),
    ORGANIZATION_TYPE VARCHAR2(30),
    CONSTRAINT ORGANIZATIONS_PK PRIMARY KEY (ID),
    CONSTRAINT ORGANIZATIONS_UQ UNIQUE (TITLE),
    CONSTRAINT ORGANIZATIONS_TYPE_FK
        FOREIGN KEY (ORGANIZATION_TYPE)
        REFERENCES ORGANIZATIONS_TYPES (TYPE)
);
CREATE TABLE PERSONS (
    ID NUMBER(6,0),
    FIRSTNAME VARCHAR2(50) NOT NULL,
    LASTNAME VARCHAR2(50) NOT NULL,
    EMAIL VARCHAR2(50) NOT NULL,
    PHONE VARCHAR2(20),
    IS_ACCOMMODATION_REQUIRED NUMBER(1,0),
    IS_ASSISTANCE_REQUIRED NUMBER(1,0),
    ORGANIZATION_ID NUMBER(6,0),
    CONSTRAINT PERSONS_PK PRIMARY KEY (ID),
    CONSTRAINT PERSONS_UQ UNIQUE (EMAIL),
    CONSTRAINT PERSONS_ORGANIZATION_ID_FK
        FOREIGN KEY (ORGANIZATION_ID)
        REFERENCES ORGANIZATIONS (ID)
);
ALTER TABLE ORGANIZATIONS ADD (
 CONSTRAINT ORGANIZATIONS_CONTACT_ID_FK
 FOREIGN KEY (CONTACT_PERSON_ID)
 REFERENCES PERSONS (ID)
);
CREATE TABLE LOCATIONS (
    ID NUMBER(6,0) NOT NULL,
    ORGANIZATION_ID NUMBER(5,0) NOT NULL,
    ADDRESS VARCHAR2(100) NOT NULL,
    HAS_PARKING NUMBER(1,0),
    CONSTRAINT LOCATIONS_PK PRIMARY KEY (ID),
    CONSTRAINT LOCATIONS_UQ UNIQUE (ORGANIZATION_ID, ADDRESS),
    CONSTRAINT LOCATIONS_ORGANIZATION_ID_FK
        FOREIGN KEY (ORGANIZATION_ID)
        REFERENCES ORGANIZATIONS (ID)
);
CREATE TABLE AUDITORIUMS(
    ID NUMBER(6,0) NOT NULL,
    LOCATION_ID NUMBER(6,0) NOT NULL,
    AUDITORIUM VARCHAR2(30) NOT NULL,
    PLACES NUMBER(3,0),
    HAS_WORKSTATION NUMBER(1,0),
    CONSTRAINT AUDITORIUMS_PK PRIMARY KEY (ID),
    CONSTRAINT AUDITORIUMS_UQ UNIQUE (AUDITORIUM),
    CONSTRAINT AUDITORIUMS_LOCATION_ID_FK
        FOREIGN KEY (LOCATION_ID)
        REFERENCES LOCATIONS (ID)
);
CREATE TABLE HOTELS(
    ID NUMBER(6,0) NOT NULL,
    LOCATION_ID NUMBER(6,0) NOT NULL,
    HOTEL_STARS NUMBER(1,0),
    PRICE NUMBER(3,2),
    ROOMS NUMBER(3,0),
    CONSTRAINT HOTELS_PK PRIMARY KEY (ID),
    CONSTRAINT HOTELS_UQ UNIQUE (LOCATION_ID),
    CONSTRAINT HOTELS_LOCATION_ID_FK
        FOREIGN KEY (LOCATION_ID)
        REFERENCES LOCATIONS (ID)
);
CREATE TABLE ACCOMMODATIONS(
    ID NUMBER(6,0) NOT NULL,
    HOTEL_ID NUMBER(6,0) NOT NULL,
    PERSON_ID NUMBER(6,0) NOT NULL,
    START_DATE DATE,
    END_DATE DATE,
    CONSTRAINT ACCOMMODATIONS_PK PRIMARY KEY (ID),
    CONSTRAINT ACCOMMODATIONS_UQ UNIQUE (PERSON_ID,START_DATE),
    CONSTRAINT ACCOMMODATIONS_HOTEL_ID_FK
        FOREIGN KEY (HOTEL_ID)
        REFERENCES HOTELS (ID),
    CONSTRAINT ACCOMMODATIONS_PERSON_ID_FK
        FOREIGN KEY (PERSON_ID)
        REFERENCES PERSONS (ID)
);
CREATE TABLE CONFERENCES(
    CODE VARCHAR2(10) NOT NULL,
    TITLE VARCHAR2(50) NOT NULL,
    START_DATE DATE,
    END_DATE DATE,
    CONSTRAINT CONFERENCES_PK PRIMARY KEY (CODE)
);
CREATE TABLE SECTIONS(
    ID NUMBER(6,0) NOT NULL,
    TITLE VARCHAR2(50) NOT NULL,
    CONFERENCE_CODE VARCHAR2(10) NOT NULL,
    CONSTRAINT SECTIONS_PK PRIMARY KEY (ID),
    CONSTRAINT SECTIONS_CONFERENCE_CODE_FK
        FOREIGN KEY (CONFERENCE_CODE)
        REFERENCES CONFERENCES (CODE)
);
CREATE TABLE REFERATS(
    ID NUMBER(6,0) NOT NULL,
    SECTION_ID NUMBER(6,0) NOT NULL,
    TITLE VARCHAR2(50) NOT NULL,
    DESCRIPTION VARCHAR2(2000),
    CONSTRAINT REFERATS_PK PRIMARY KEY (ID),
    CONSTRAINT REFERATS_SECTION_ID_FK
        FOREIGN KEY (SECTION_ID)
        REFERENCES SECTIONS (ID)
);
CREATE TABLE REFERAT_PARTS(
    PART VARCHAR2(10) NOT NULL,
    WEIGHT NUMBER(2,0),
    CONSTRAINT REFERAT_PARTS_PK PRIMARY KEY (PART)
);
CREATE TABLE REFERAT_PARTS_SUBMITTED(
    REFERAT_ID NUMBER(6,0) NOT NULL,
    REFERAT_PART VARCHAR2(10) NOT NULL,
    DATE_SUBMITTED DATE,
    CONSTRAINT REFERAT_PARTS_OK_PK PRIMARY KEY (REFERAT_ID,REFERAT_PART),
    CONSTRAINT REFERAT_PARTS_OK_REFERAT_ID_FK
        FOREIGN KEY (REFERAT_ID)
        REFERENCES REFERATS (ID),
    CONSTRAINT REFERAT_PARTS_OK_REFERAT_PART
        FOREIGN KEY (REFERAT_PART)
        REFERENCES REFERAT_PARTS (PART)
);
CREATE TABLE LECTURES(
    ID NUMBER(6,0) NOT NULL,
    IS_WORKSHOP NUMBER(1,0),
    REFERAT_ID NUMBER(6,0) NOT NULL,
    AUDITORIUM_ID NUMBER(6,0) NOT NULL,
    START_DATETIME DATE NOT NULL,
    END_DATETIME DATE,
    IS_FREE NUMBER(1,0) DEFAULT 1,
    CONSTRAINT LECTURES_PK PRIMARY KEY (ID),
    CONSTRAINT LECTURES_UQ UNIQUE (AUDITORIUM_ID, START_DATETIME),
    CONSTRAINT LECTURES_REFERAT_ID_FK
        FOREIGN KEY (REFERAT_ID)
        REFERENCES REFERATS (ID),
    CONSTRAINT LECTURES_AUDITORIUM_ID
        FOREIGN KEY (AUDITORIUM_ID)
        REFERENCES AUDITORIUMS (ID)
);
CREATE TABLE RATINGS(
    RATING VARCHAR2(10) NOT NULL,
    CONSTRAINT RATINGS_PK PRIMARY KEY (RATING)
);
CREATE TABLE PARTICIPANTS(
    PERSON_ID NUMBER(6,0) NOT NULL,
    LECTURE_ID NUMBER(6,0) NOT NULL,
    RATING VARCHAR2(10),
    CHECKED_IN NUMBER(1,0),
    CONSTRAINT PARTICIPANTS_PK PRIMARY KEY (PERSON_ID, LECTURE_ID),
    CONSTRAINT PARTICIPANTS_PERSON_ID_FK
        FOREIGN KEY (PERSON_ID)
        REFERENCES PERSONS (ID),
    CONSTRAINT PARTICIPANTS_LECTURE_ID_FK
        FOREIGN KEY (LECTURE_ID)
        REFERENCES LECTURES (ID),
    CONSTRAINT PARTICIPANTS_RATING_FK
        FOREIGN KEY (RATING)
        REFERENCES RATINGS (RATING)
);
CREATE TABLE LECTURERS(
    ID NUMBER(6,0) NOT NULL,
    PERSON_ID NUMBER(6,0) NOT NULL,
    LECTURE_ID NUMBER(6,0) NOT NULL,
    CONSTRAINT LECTURERS_PK PRIMARY KEY (ID),
    CONSTRAINT LECTURERS_UQ UNIQUE (PERSON_ID, LECTURE_ID),
    CONSTRAINT LECTURERS_PERSON_ID_FK
        FOREIGN KEY (PERSON_ID)
        REFERENCES PERSONS (ID),
    CONSTRAINT LECTURERS_LECTURE_ID_FK
        FOREIGN KEY (LECTURE_ID)
        REFERENCES LECTURES (ID)
);
CREATE TABLE HELPTEAM(
    PERSON_ID NUMBER(6,0) NOT NULL,
    IS_FULL_TYME NUMBER(1,0),
    HAS_DRIVING_LICENCE NUMBER(1,0),
    CONSTRAINT HELPTEAM_PK PRIMARY KEY (PERSON_ID),
    CONSTRAINT HELPTEAM_PERSON_ID_FK
        FOREIGN KEY (PERSON_ID)
        REFERENCES PERSONS (ID)
);
CREATE TABLE ASSISTANCE(
    HELPTEAM_PERSON_ID NUMBER(6,0) NOT NULL,
    ASSISTED_PERSON_ID NUMBER(6,0) NOT NULL,
    CONSTRAINT ASSIST_PK PRIMARY KEY (HELPTEAM_PERSON_ID, ASSISTED_PERSON_ID),
    CONSTRAINT ASSIST_HELPTEAM_PERSON_ID_FK
        FOREIGN KEY (HELPTEAM_PERSON_ID)
        REFERENCES HELPTEAM (PERSON_ID),
    CONSTRAINT ASSIST_ASSISTED_PERSON_ID_FK
        FOREIGN KEY (ASSISTED_PERSON_ID)
        REFERENCES PERSONS (ID)
);
CREATE TABLE CARS (
    LICENCE_PLATE VARCHAR2(6) NOT NULL,
    MANUFACTURER VARCHAR2(20),
    MODEL VARCHAR2(20),
    YEAR DATE,
    IS_AVAILABLE NUMBER(1,0),
    DRIVER_PERSON_ID NUMBER(6,0),
    CONSTRAINT CARS_PK PRIMARY KEY (LICENCE_PLATE),
    CONSTRAINT CARS_DRIVER_PERSON_ID_FK
        FOREIGN KEY (DRIVER_PERSON_ID)
        REFERENCES HELPTEAM (PERSON_ID)
);










