ORGANIZATIONS_TYPES (
    TYPE VARCHAR2(30)
)
ORGANIZATIONS (
    ID NUMBER(60) NOT NULL
    TITLE VARCHAR2(50) NOT NULL
    CONTACT_PERSON_ID NUMBER(60)
    ORGANIZATION_TYPE VARCHAR2(30)
)
PERSONS (
    ID NUMBER(60)
    FIRSTNAME VARCHAR2(50) NOT NULL
    LASTNAME VARCHAR2(50) NOT NULL
    EMAIL VARCHAR2(50) NOT NULL
    PHONE VARCHAR2(20)
    IS_ACCOMMODATION_REQUIRED NUMBER(10)
    IS_ASSISTANCE_REQUIRED NUMBER(10)
    ORGANIZATION_ID NUMBER(60)
)
ALTER TABLE ORGANIZATIONS ADD (
)
LOCATIONS (
    ID NUMBER(60) NOT NULL
    ORGANIZATION_ID NUMBER(50) NOT NULL
    ADDRESS VARCHAR2(100) NOT NULL
    HAS_PARKING NUMBER(10)
)
AUDITORIUMS(
    ID NUMBER(60) NOT NULL
    LOCATION_ID NUMBER(60) NOT NULL
    AUDITORIUM VARCHAR2(30) NOT NULL
    PLACES NUMBER(30)
    HAS_WORKSTATION NUMBER(10)
)
HOTELS(
    ID NUMBER(60) NOT NULL
    LOCATION_ID NUMBER(60) NOT NULL
    HOTEL_STARS NUMBER(10)
    PRICE NUMBER(32)
    ROOMS NUMBER(30)
)
ACCOMMODATIONS(
    ID NUMBER(60) NOT NULL
    HOTEL_ID NUMBER(60) NOT NULL
    PERSON_ID NUMBER(60) NOT NULL
    START_DATE DATE
    END_DATE DATE
)
CONFERENCES(
    CODE VARCHAR2(10) NOT NULL
    TITLE VARCHAR2(50) NOT NULL
    START_DATE DATE
    END_DATE DATE
)
SECTIONS(
    ID NUMBER(60) NOT NULL
    TITLE VARCHAR2(50) NOT NULL
    CONFERENCE_CODE VARCHAR2(10) NOT NULL
)
REFERATS(
    ID NUMBER(60) NOT NULL
    SECTION_ID NUMBER(60) NOT NULL
    TITLE VARCHAR2(50) NOT NULL
    DESCRIPTION VARCHAR2(2000)
)
REFERAT_PARTS(
    PART VARCHAR2(10) NOT NULL
    WEIGHT NUMBER(20)
)
REFERAT_PARTS_SUBMITTED(
    REFERAT_ID NUMBER(60) NOT NULL
    REFERAT_PART VARCHAR2(10) NOT NULL
    DATE_SUBMITTED DATE
)
LECTURES(
    ID NUMBER(60) NOT NULL
    IS_WORKSHOP NUMBER(10)
    REFERAT_ID NUMBER(60) NOT NULL
    AUDITORIUM_ID NUMBER(60) NOT NULL
    START_DATETIME DATE NOT NULL
    END_DATETIME DATE
    IS_FREE NUMBER(10) DEFAULT 1
)
RATINGS(
    RATING VARCHAR2(10) NOT NULL
)
PARTICIPANTS(
    PERSON_ID NUMBER(60) NOT NULL
    LECTURE_ID NUMBER(60) NOT NULL
    RATING VARCHAR2(10)
    CHECKED_IN NUMBER(10)
)
LECTURERS(
    ID NUMBER(60) NOT NULL
    PERSON_ID NUMBER(60) NOT NULL
    LECTURE_ID NUMBER(60) NOT NULL
)
HELPTEAM(
    PERSON_ID NUMBER(60) NOT NULL
    IS_FULL_TYME NUMBER(10)
    HAS_DRIVING_LICENCE NUMBER(10)
)
ASSISTANCE(
    HELPTEAM_PERSON_ID NUMBER(60) NOT NULL
    ASSISTED_PERSON_ID NUMBER(60) NOT NULL
)
CARS (
    LICENCE_PLATE VARCHAR2(6) NOT NULL
    MANUFACTURER VARCHAR2(20)
    MODEL VARCHAR2(20)
    YEAR DATE
    IS_AVAILABLE NUMBER(10)
    DRIVER_PERSON_ID NUMBER(60)
)










